 
Vagrant.configure("2") do |config|
 config.vm.define "host1" do |centos|
  
	centos.vm.box = "centos/8"
	centos.vm.network "forwarded_port", guest: 80, host: 8083
    centos.vm.network "private_network", ip: "100.104.146.213"
    centos.vm.synced_folder ".", "/vagrant_data"
    centos.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "512"
    end
 centos.vm.provision "shell", inline: <<-SHELL
		yum install curl -y
		yum install wget -y
		yum install vim -y 
		yum install git -y
		sudo adduser updater
		passwd -f -u updater
		sudo gpasswd -a updater wheel
    SHELL
 end
end
