
Vagrant.configure("2") do |config|
    config.vm.define "host3" do |centos|
    centos.vm.box = "centos/8"
    centos.vm.network "forwarded_port", guest: 80, host: 8085
    centos.vm.network "private_network", ip: "100.104.146.215"
    #/config1.vm.synced_folder ".", "/vagrant_data"
    centos.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "1024"
	   vb.cpus = "2"
    end
    centos.vm.provision "shell", inline: <<-SHELL
        sudo yum install -y vim git wget curl mc
		sudo adduser updater
		sudo passwd updater
		sudo visudo
		added string `insider ALL=(ALL) NOPASSWD: ALL`
		    SHELL
  end
end