version: '3.3'

services:
  service_01:
    sonarr:
	 image: ghcr.io/linuxserver/sonarr
      container_name: sonarr
	 volumes:
		- /path/to/data:/config
		- /path/to/tvseries:/tv
		- /path/to/downloadclient-downloads:/downloads
      ports:
		- 8989:8989
  service_02:
    radarr:
     image: ghcr.io/linuxserver/radarr
     container_name: radarr
     volumes:
      - /path/to/data:/config
      - /path/to/movies:/movies
      - /path/to/downloadclient-downloads:/downloads
     ports:
      - 7878:7878
     restart: unless-stopped
volumes:
        local_data:
            external:
                name: local_data