
Vagrant.configure("2") do |config|
    config.vm.define "host1" do |debian|
    debian.vm.box = "debian/jessie64"
    debian.vm.network "forwarded_port", guest: 80, host: 8083
    debian.vm.network "private_network", ip: "100.104.146.213"
    debian.vm.synced_folder ".", "/vagrant_data"
    debian.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = "512"
    end
    debian.vm.provision "shell", inline: <<-SHELL
        sudo su
		apt update
		sudo apt upgrade -y 
		sudo apt install vim git wget curl  -y 
    SHELL
  end
end